### ISSUE TITLE
Why should I use this plugin

### ISSUE THREAD

**Issue by dpinart** [aurelia/html-import-template-loader#14]
Hi,
I'm a bit confused about what this plugin serves for. Firstly, I thought that I should use this plugin in order to being able to use polymer widgets in my app, but I can use polymer without html-import-template-loader. Then I thought it would allow to bundle polymer widget along with my aurelia views and widgets without the need to use vulcanize but as said in [issue 11](https://github.com/aurelia/html-import-template-loader/issues/11) vulcanize is still required to bundle polymer.
At this point, I don't know why should I use this plugin, is there any performance gain by importing html views when using polymer?

**Comment by EisenbergEffect** [comment]
This plugin is present for those who really prefer to use html imports to load their views. If you don't need/want that, then you don't need to use it.

At some point, I think html imports were required for Polymer. That may have changed over the last 18 months or so since the initial plugin was written.
